'use client';

import GlobalModal from '@/components/Modal/GlobalModal';
import MobileLayout from '@/components/layout/mobile-layout';
import ReactQueryProvider from '@/lib/react-query/ReactQueryProvider';
import StyledComponentsRegistry from '@/lib/registry';
import { GlobalStyle } from '@/styles/GlobalStyle';
import { theme } from '@/styles/theme';
import localFont from 'next/font/local';
import { RecoilRoot } from 'recoil';
import { ThemeProvider } from 'styled-components';

// export const metadata: Metadata = {
//   title: '맛셔너리',
//   description: 'Generated by create next app',
// };

const myFont = localFont({
  src: './fonts/Galmuri9.woff2',
  display: 'swap',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head></head>
      <body className={myFont.className}>
        <StyledComponentsRegistry>
          <RecoilRoot>
            <ThemeProvider theme={theme}>
              <GlobalStyle />
              <GlobalModal />
              <ReactQueryProvider>
                <MobileLayout>{children}</MobileLayout>
              </ReactQueryProvider>
            </ThemeProvider>
          </RecoilRoot>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
