'use client';

import StyledComponentsRegistry from '@/lib/registry';
import { GlobalStyle } from '@/styles/GlobalStyle';
import { theme } from '@/styles/theme';
import type { Metadata } from 'next';
import { ThemeProvider } from 'styled-components';

// 해당 부분에서 export를 하면 Error가 발생합니다.
const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    as="style"
                    crossOrigin=""
                    href="https://cdn.jsdelivr.net/npm/galmuri/dist/galmuri.css"
                />
            </head>
            <body>
                <StyledComponentsRegistry>
                    <ThemeProvider theme={theme}>
                        <GlobalStyle />
                        {children}
                    </ThemeProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
